### ISSUE TITLE
Notification Emails not being sent

### ISSUE THREAD

**Issue by donaldali** [rails-school/school#179]
When notification for a new lesson is sent, the SendGrid addon for the `rssf-worker` heroku app seems to be sending emails instead of the SendGrid addon for the `rssf` heroku app. As a result no one receives emails about new Rails School lessons.

**Comment by gkop** [comment]
Somehow the heroku config for rssf-worker changed to incorrect sendgrid params. I have fixed this. However because most of our users have gmail and gmail blocks unauthenticated yahoo addresses like Donald's, I had to try and send the gmail users messages from my own account. But I screwed this up and blew all our sendgrid credits for the day. I will send the messages to the gmail users tomorrow morning.
