### ISSUE TITLE
Should we be proactive about switching our chat to Gitter?

### ISSUE THREAD

**Issue by gkop** [rails-school/school#197]
The problem is Slack doesn't have the "public link to join channel as guest" functionality that Hipchat had.

I think we are pretty happy in Coshx Slack at the moment, but it's not as transparent and open as our old Hipchat room used to be.

The logical solution is destroying our Slack channel and moving Rails School chat to https://gitter.im/rails-school/chat , which is completely public with zero friction to join. I only have a small amount of experience with Gitter, but it seems quite ideal for our use case. The downside is that rather than always having the channel open, as we do in Slack, many of us would probably depend on Gitter's email notifications to be summoned to a conversation.

We can totally wait and see on this issue. I am on the fence personally.

I would however like to update https://github.com/rails-school/school/blob/master/STARTING_A_LOCAL_SCHOOL.md#getting-help either pointing to Gitter or giving instructions how to request a Slack invite.

/cc @rails-school/owners

**Comment by acadet** [comment]
Moving to Gitter sounds start. Unless we can make our Slack room public - not sure about it.
Also you have a desktop application for Gitter.

**Comment by gkop** [comment]
Maybe we should try this first: https://wiredcraft.com/blog/using-slack-as-a-public-chat/

**Comment by btaitelb** [comment]
I don't have a lot of experience with gitter, but when I've checked it out, it felt like the conversations were async, which I think is going to be the case here (especially since most of us would just be using it for railsschool). For async communication, github issues work great. For real-time communication, there are the railsschool events themselves, which is probably the best place to sync up if you're creating a new school.

 I'm on board with trying out gitter and seeing how are usage is over time.

**Comment by gkop** [comment]
For the time being, I have set up http://slackin.railsschool.org/ . I just need an API key from @btaitelb or @acadet that grants invites. You can get this API key https://api.slack.com/web and either slack it to me or replace my API key with it in `/etc/init/slackin-railsschool.conf` on runcible.
